#!/usr/bin/env python3
"""Focused tests for Unicode identifier table generation helpers."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent


def load_generator():
    spec = importlib.util.spec_from_file_location(
        "generate_unicode_id_tables",
        SCRIPT_DIR / "generate-unicode-id-tables.py",
    )
    if spec is None or spec.loader is None:
        raise RuntimeError("failed to load generate-unicode-id-tables.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules["generate_unicode_id_tables"] = module
    spec.loader.exec_module(module)
    return module


def main() -> int:
    generator = load_generator()
    text = """0041..005A ; ID_Start # Lu
0061 ; ID_Start
0062 ; ID_Start
0030 ; ID_Continue
0031..0032 ; ID_Continue
00AA ; Other_Property
"""
    assert generator.parse_property(text, "ID_Start") == [(0x41, 0x5A), (0x61, 0x62)]
    assert generator.parse_property(text, "ID_Continue") == [(0x30, 0x32)]

    emitted = generator.emit(
        "17.0.0",
        {
            "ID_Start": [(0x41, 0x5A)],
            "ID_Continue": [(0x30, 0x39), (0x41, 0x5A)],
        },
    )
    assert emitted.startswith(
        "// AUTOGENERATED by scripts/generate-unicode-id-tables.py — do not edit by hand.\n"
    )
    assert """/// 1 ranges, sorted and coalesced.
let id_start_ranges : Array[(Int, Int)] = [
  (0x0041, 0x005A),
]""" in emitted
    assert """/// 2 ranges, sorted and coalesced.
let id_continue_ranges : Array[(Int, Int)] = [
  (0x0030, 0x0039),
  (0x0041, 0x005A),
]""" in emitted
    assert emitted.endswith("}\n\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
