#!/usr/bin/env python3
"""
Generate `lexer/unicode_id.mbt` from the official Unicode `DerivedCoreProperties.txt`.

ECMAScript §11.6 specifies `IdentifierStartChar`/`IdentifierPartChar` in terms of
the Unicode `ID_Start` and `ID_Continue` properties (UAX #31 R1). We extract those
two property sets, merge adjacent codepoints into ranges, and emit a MoonBit file
exposing two `Int -> Bool` lookup functions backed by binary search.

Usage:
    scripts/generate-unicode-id-tables.py [--unicode-version 17.0.0]

The output is deterministic given the same Unicode version. Re-run when bumping
the Unicode target; commit the regenerated file alongside the version bump.
"""
from __future__ import annotations

import argparse
import sys
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "lexer" / "unicode_id.mbt"
URL_TEMPLATE = "https://www.unicode.org/Public/{version}/ucd/DerivedCoreProperties.txt"

PROPERTIES = ("ID_Start", "ID_Continue")


def fetch(version: str) -> str:
    url = URL_TEMPLATE.format(version=version)
    print(f"Fetching {url}", file=sys.stderr)
    with urllib.request.urlopen(url) as resp:
        return resp.read().decode("utf-8")


def parse_property(text: str, property_name: str) -> list[tuple[int, int]]:
    """Return a list of (start, end) inclusive ranges for `property_name`."""
    points: list[tuple[int, int]] = []
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        # `<codepoint>[..<codepoint>] ; PropertyName`
        cp_field, _, prop_field = line.partition(";")
        if prop_field.strip() != property_name:
            continue
        cp_field = cp_field.strip()
        if ".." in cp_field:
            lo_s, hi_s = cp_field.split("..")
            points.append((int(lo_s, 16), int(hi_s, 16)))
        else:
            cp = int(cp_field, 16)
            points.append((cp, cp))
    return _merge(points)


def _merge(ranges: list[tuple[int, int]]) -> list[tuple[int, int]]:
    """Sort and coalesce adjacent ranges so the table is minimal."""
    if not ranges:
        return []
    ranges.sort()
    merged = [ranges[0]]
    for lo, hi in ranges[1:]:
        prev_lo, prev_hi = merged[-1]
        if lo <= prev_hi + 1:
            merged[-1] = (prev_lo, max(prev_hi, hi))
        else:
            merged.append((lo, hi))
    return merged


def emit(version: str, tables: dict[str, list[tuple[int, int]]]) -> str:
    out: list[str] = []
    out.append("// AUTOGENERATED by scripts/generate-unicode-id-tables.py — do not edit by hand.")
    out.append(f"// Source: DerivedCoreProperties.txt @ Unicode {version}")
    out.append(f"// Properties: {', '.join(PROPERTIES)} (ECMAScript §11.6 / UAX #31 R1)")
    out.append("")
    for name in PROPERTIES:
        ranges = tables[name]
        out.append("///|")
        out.append(f"/// {len(ranges)} ranges, sorted and coalesced.")
        out.append(f"let {_table_name(name)} : Array[(Int, Int)] = [")
        for lo, hi in ranges:
            out.append(f"  (0x{lo:04X}, 0x{hi:04X}),")
        out.append("]")
        out.append("")
    out.append(_LOOKUP_FNS)
    return "\n".join(out) + "\n"


def _table_name(prop: str) -> str:
    return prop.lower() + "_ranges"


_LOOKUP_FNS = """///|
/// Binary search across sorted, non-overlapping `(lo, hi)` ranges.
fn in_ranges(table : ArrayView[(Int, Int)], cp : Int) -> Bool {
  let mut lo = 0
  let mut hi = table.length()
  while lo < hi {
    let mid = (lo + hi) / 2
    let (rlo, rhi) = table[mid]
    if cp < rlo {
      hi = mid
    } else if cp > rhi {
      lo = mid + 1
    } else {
      return true
    }
  }
  false
}

///|
/// Returns true if `cp` has the Unicode `ID_Start` property (UAX #31 / ES262 §11.6).
fn is_id_start(cp : Int) -> Bool {
  in_ranges(id_start_ranges[:], cp)
}

///|
/// Returns true if `cp` has the Unicode `ID_Continue` property.
fn is_id_continue(cp : Int) -> Bool {
  in_ranges(id_continue_ranges[:], cp)
}
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--unicode-version", default="17.0.0")
    ap.add_argument("--output", type=Path, default=OUTPUT)
    args = ap.parse_args()

    text = fetch(args.unicode_version)
    tables = {name: parse_property(text, name) for name in PROPERTIES}
    # Pin encoding and newline so regen is hash-stable across platforms.
    args.output.write_text(emit(args.unicode_version, tables), encoding="utf-8", newline="\n")
    print(f"Wrote {args.output} ({sum(len(v) for v in tables.values())} ranges)", file=sys.stderr)


if __name__ == "__main__":
    main()
