#!/usr/bin/env node

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HONO_VERSION = "4.12.31";
const ESBUILD_VERSION = "0.27.7";
const HONO_TARBALL_URL =
  `https://registry.npmjs.org/hono/-/hono-${HONO_VERSION}.tgz`;
const HONO_TARBALL_SHA256 =
  "d32c7ffb9ea3f7c9268d4f942e811a4bcd11afd96ece7b3a47d7ba96b6ed0596";
const EXPECTED_BUNDLE_BYTES = 65441;
const EXPECTED_BUNDLE_SHA256 =
  "124d47855cb3c634399e04819f8bdeb5da8848b17d989d9099b98bd3e2f16603";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = realpathSync(resolve(scriptDir, ".."));
const outputPath = join(
  repositoryRoot,
  "integration/external_consumer/hono_4_12_31_bundle_test.mbt",
);
const staging = mkdtempSync(join(tmpdir(), "js-engine-hono-acceptance-"));

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

try {
  execFileSync(
    "npm",
    [
      "pack",
      `hono@${HONO_VERSION}`,
      "--ignore-scripts",
      "--pack-destination",
      staging,
    ],
    { cwd: staging, stdio: "inherit" },
  );
  const tarballPath = join(staging, `hono-${HONO_VERSION}.tgz`);
  const tarballHash = sha256(readFileSync(tarballPath));
  if (tarballHash !== HONO_TARBALL_SHA256) {
    throw new Error(
      `unexpected Hono tarball SHA-256: ${tarballHash} (expected ${HONO_TARBALL_SHA256})`,
    );
  }
  execFileSync("tar", ["-xzf", tarballPath], { cwd: staging });

  const entryPath = join(staging, "entry.mjs");
  writeFileSync(
    entryPath,
    [
      'import { Hono } from "./package/dist/index.js";',
      "globalThis.__HonoAcceptance = { Hono };",
      "",
    ].join("\n"),
  );
  const bundlePath = join(staging, "hono-esnext.js");
  execFileSync(
    "npx",
    [
      "--yes",
      `esbuild@${ESBUILD_VERSION}`,
      "entry.mjs",
      "--bundle",
      "--format=iife",
      "--platform=neutral",
      "--target=esnext",
      "--log-level=warning",
      "--outfile=hono-esnext.js",
    ],
    { cwd: staging, stdio: "inherit" },
  );

  const bundle = readFileSync(bundlePath);
  const bundleHash = sha256(bundle);
  if (bundle.length !== EXPECTED_BUNDLE_BYTES) {
    throw new Error(
      `unexpected bundle size: ${bundle.length} (expected ${EXPECTED_BUNDLE_BYTES})`,
    );
  }
  if (bundleHash !== EXPECTED_BUNDLE_SHA256) {
    throw new Error(
      `unexpected bundle SHA-256: ${bundleHash} (expected ${EXPECTED_BUNDLE_SHA256})`,
    );
  }
  const source = bundle.toString("utf8");
  const moonbit = [
    "// Generated by scripts/generate_hono_acceptance_fixture.mjs; do not edit.",
    `// Source: ${HONO_TARBALL_URL}`,
    `// Hono tarball SHA-256: ${HONO_TARBALL_SHA256}`,
    `// Bundler: esbuild ${ESBUILD_VERSION} --bundle --format=iife --platform=neutral --target=esnext`,
    `// Bundle bytes: ${bundle.length}`,
    `// Bundle SHA-256: ${bundleHash}`,
    "///|",
    "pub const HONO_4_12_31_BUNDLE =",
    ...source.split("\n").map((line) => `  #|${line}`),
    "",
  ].join("\n");
  writeFileSync(outputPath, moonbit);
  process.stdout.write(
    `wrote ${outputPath}\nbytes=${bundle.length}\nsha256=${bundleHash}\n`,
  );
} finally {
  rmSync(staging, { recursive: true, force: true });
}
